package com.ratelimiter.service.algorithm;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import java.util.List;
import java.util.NavigableMap;
import java.util.TreeMap;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.From;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;
import net.jqwik.api.constraints.LongRange;
import net.jqwik.api.constraints.Size;

/**
 * Property-based tests for {@link SlidingWindowLog}, generated by jqwik over
 * randomized limit / window / request-timing inputs.
 *
 * <ul>
 *   <li>P1 — never more than {@code limit} events are allowed in any window of
 *       length {@code windowMillis} (this is the defining invariant a sliding
 *       window must uphold and the one fixed windows get wrong).</li>
 *   <li>P3 — the accounting is consistent: remaining + in-window count == limit,
 *       and neither goes negative.</li>
 * </ul>
 */
class SlidingWindowProperties {

    private static final double EPS = 1e-6;

    @Provide("deltas")
    Arbitrary<Long> deltas() {
        return Arbitraries.longs().between(0L, 5000L);
    }

    @Property(tries = 20000)
    void neverMoreThanNAllowedInAnySlidingWindow(
            @ForAll @IntRange(min = 1, max = 50) int limit,
            @ForAll @LongRange(min = 1000, max = 100000) long windowMillis,
            @ForAll @Size(max = 200) List<@From("deltas") Long> deltas) {

        SlidingWindowLog log = new SlidingWindowLog(limit, windowMillis);
        NavigableMap<Long, Integer> events = new TreeMap<>();
        long now = 0;

        for (Long delta : deltas) {
            now += Math.max(0, delta);
            SlidingWindowLog.Result result = log.consume(events, now);
            events = result.state();

            long inWindow = events.values().stream().mapToLong(Integer::longValue).sum();
            // At any instant, the number of events within the trailing window can
            // never exceed the limit.
            assertThat(inWindow)
                    .as("in-window count (limit=%d, window=%d)", limit, windowMillis)
                    .isLessThanOrEqualTo(limit);
        }
    }

    @Property(tries = 20000)
    void accountingConsistentWithLimit(
            @ForAll @IntRange(min = 1, max = 50) int limit,
            @ForAll @LongRange(min = 1000, max = 100000) long windowMillis,
            @ForAll @Size(max = 200) List<@From("deltas") Long> deltas) {

        SlidingWindowLog log = new SlidingWindowLog(limit, windowMillis);
        NavigableMap<Long, Integer> events = new TreeMap<>();
        long now = 0;

        for (Long delta : deltas) {
            now += Math.max(0, delta);
            SlidingWindowLog.Result result = log.consume(events, now);
            events = result.state();

            long inWindow = events.values().stream().mapToLong(Integer::longValue).sum();
            double remaining = result.decision().remaining();
            assertThat(remaining).isGreaterThanOrEqualTo(0.0);
            assertThat(inWindow).isGreaterThanOrEqualTo(0);
            // Accounting invariant: remaining always equals limit minus the number
            // of events currently counted in the window.
            assertThat(remaining).isCloseTo((double) limit - inWindow, within(EPS));
        }
    }
}
