package com.ratelimiter.service.algorithm;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import java.util.List;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Combinators;
import net.jqwik.api.ForAll;
import net.jqwik.api.From;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.constraints.IntRange;
import net.jqwik.api.constraints.Size;

/**
 * Property-based tests for {@link TokenBucket}, generated by jqwik over
 * randomized capacity / rate / request-sequence inputs.
 *
 * <p>Property tests are the highest-credibility artifact here because they attack
 * the invariants with inputs the author did not hand-pick, including boundary
 * and adversarial cases, and jqwik shrinks any failure to a minimal
 * counterexample. The three invariants proved below are the ones that make a
 * token bucket correct:
 *
 * <ul>
 *   <li>P1 — at any single instant (no refill) you can never grant more than the
 *       capacity.</li>
 *   <li>P2 — refill never pushes the balance above capacity, for any elapsed
 *       time, and the balance never goes negative.</li>
 *   <li>P3 — within a non-refilling burst the accounting balances exactly:
 *       consumed + remaining == capacity (no tokens created or lost).</li>
 * </ul>
 */
class TokenBucketProperties {

    private static final double EPS = 1e-6;

    /** A single candidate request: how many tokens it wants and how much time
     *  elapsed since the previous observation. */
    private record Request(double requested, long deltaMillis) {
    }

    /** Generates the per-request inputs; shared by all three properties. */
    @Provide("requests")
    Arbitrary<Request> requests() {
        return Combinators.combine(
                Arbitraries.doubles().between(0.1, 5.0),
                Arbitraries.longs().between(0L, 10_000_000L))
                .as((requested, delta) -> new Request(requested, delta));
    }

    @Property(tries = 20000)
    void neverMoreThanLimitAllowedInAnySequence(
            @ForAll @IntRange(min = 1, max = 100) int capacity,
            @ForAll @IntRange(min = 0, max = 50) int ratePerSecond,
            @ForAll @Size(max = 100) List<@From("requests") Request> requests) {

        TokenBucket bucket = new TokenBucket(capacity, ratePerSecond);
        TokenBucket.State state = TokenBucket.State.full(capacity, 0);
        long now = 0;
        double consumedInCurrentBurst = 0;

        for (Request request : requests) {
            boolean timeAdvanced = request.deltaMillis() > 0;
            if (timeAdvanced) {
                // Time moved forwards, so the previous burst is over.
                consumedInCurrentBurst = 0;
            }
            now += request.deltaMillis();
            TokenBucket.Result result = bucket.consume(state, request.requested(), now);
            if (result.decision().allowed()) {
                consumedInCurrentBurst += request.requested();
            }
            if (!timeAdvanced) {
                // No refill happened inside this burst, so the only tokens that
                // could be granted are the ones present at burst start: at most
                // the capacity.
                assertThat(consumedInCurrentBurst)
                        .as("within a no-refill burst")
                        .isLessThanOrEqualTo((double) capacity + EPS);
            }
            state = result.state();
        }
    }

    @Property(tries = 20000)
    void refillNeverExceedsCapacityForAnyElapsedTime(
            @ForAll @IntRange(min = 1, max = 100) int capacity,
            @ForAll @IntRange(min = 0, max = 50) int ratePerSecond,
            @ForAll @Size(max = 100) List<@From("requests") Request> requests) {

        TokenBucket bucket = new TokenBucket(capacity, ratePerSecond);
        TokenBucket.State state = TokenBucket.State.full(capacity, 0);
        long now = 0;

        for (Request request : requests) {
            now += request.deltaMillis();
            TokenBucket.Result result = bucket.consume(state, request.requested(), now);
            double remaining = result.decision().remaining();
            assertThat(remaining)
                    .as("remaining stays non-negative")
                    .isGreaterThanOrEqualTo(0.0);
            assertThat(remaining)
                    .as("refill never exceeds capacity (elapsed=%d ms)", request.deltaMillis())
                    .isLessThanOrEqualTo((double) capacity);
            assertThat(result.state().tokens())
                    .isGreaterThanOrEqualTo(0.0)
                    .isLessThanOrEqualTo((double) capacity);
            state = result.state();
        }
    }

    @Property(tries = 20000)
    void remainingPlusConsumedEqualsLimitInvariant(
            @ForAll @IntRange(min = 1, max = 100) int capacity,
            @ForAll @IntRange(min = 0, max = 50) int ratePerSecond,
            @ForAll @Size(max = 100) List<@From("requests") Request> requests) {

        TokenBucket bucket = new TokenBucket(capacity, ratePerSecond);
        TokenBucket.State state = TokenBucket.State.full(capacity, 0);
        double consumed = 0;

        // Pin every request to the same instant so no refill occurs: the bucket
        // starts full and strictly drains, which makes the ledger checkable.
        for (Request request : requests) {
            TokenBucket.Result result = bucket.consume(state, request.requested(), 0);
            if (result.decision().allowed()) {
                consumed += request.requested();
            }
            double remaining = result.decision().remaining();
            assertThat(remaining).isGreaterThanOrEqualTo(0.0);
            assertThat(remaining).isLessThanOrEqualTo((double) capacity);
            // Accounting invariant: tokens consumed plus tokens still in the
            // bucket always sum exactly to the capacity limit — the balance
            // ledger neither creates nor loses tokens within a burst.
            assertThat(consumed + remaining)
                    .as("consumed + remaining == capacity")
                    .isCloseTo((double) capacity, within(EPS));
            state = result.state();
        }
    }
}
